export  const defaultOption = (index=0)=>({
  name: index === 0 ? "Option 1" : `Option ${index + 1}`,
  billingType: "pay",
  billingFrequency: "",
  billingInterval: "day",
  deliveryInterval: "day",
  deliveryFrequency:1,
  minOrders: "disabled",
  maxOrders: "unlimited",
  giveDiscount: false,
  discountAmount: "",
  discountType: "amount",
  changeDiscountAfter: false,
  discountAmount2: "",
  afterOrders: "",
  discountType2: "amount",
  giveShippingDiscount: false,
  shippingDiscount: "",
  shippingAfterOrders: "",
  shippingDiscountType: "fixed",
  allowAutoActions: false,
  automationCycles: [],
  changeQtyAfterOrders: false,
  changeQtyQuantity: "",
  changeQtyAfterOrdersNum: "",
  changeQtyProducts:[],
  removeFreeProducts: false,
  removeFreeAfterOrders: "",
  removeFreeProductsList: [],
  setMinQty: false,
  minQuantity: "1",
  selectedProducts: [],
});