export const styles = {
  cycleCard: {
    border: "1px solid var(--p-color-border)",
    borderRadius: 8,
    marginBottom: 12,
    overflow: "visible",
    background: "white",
  },
  cycleHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    background: "#ebeced",
    borderRadius: "8px 8px 0 0",
    borderBottom: "1px solid #dadde0",
  },
  actionCard: {
    border: "1px solid #ebeced",
    borderRadius: 8,
    padding: "10px 12px",
    marginBottom: 10,
    background: "#ebeced",
  },
  actionThumb: {
    width: 40,
    height: 40,
    borderRadius: 6,
    objectFit: "cover",
    flexShrink: 0,
  },
  destCard: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    background: "#fcfcfc",
    marginTop: 6,
  },
  destThumb: {
    width: 32,
    height: 32,
    borderRadius: 4,
    objectFit: "cover",
    flexShrink: 0,
  },
  variantTag: {
    display: "inline-block",
    background: "#e0e2e3",
    borderRadius: 10,
    fontSize: 11,
    padding: "1px 7px",
    marginTop: 3,
    color: "#303132",
  },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 6px",
    fontSize: 16,
    borderRadius: 4,
    lineHeight: 1,
  },
  linkBtn: {
    background: "none",
    border: "none",
    color: "#005bd3",
    fontSize: 13,
    cursor: "pointer",
    padding: "4px 0",
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginTop: 6,
  },
  collapseAllBtn: {
    background: "none",
    border: "none",
    color: "#005bd3",
    fontSize: 13,
    cursor: "pointer",
    padding: 0,
  },
  dropdownSectionHeader: {
    fontSize: 12,
    fontWeight: 600,
    color: "black",
    padding: "5px 14px",
  },
  dropdownItem: {
    padding: "8px 14px",
    fontSize: 13,
    cursor: "pointer",
    color: "#2e2f2f",
  },
  radioLabel: {
    display: "flex",
    alignItems: "center",
    fontSize: 13,
    cursor: "pointer",
    color: "#303030",
  },
};