api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "admin-update"
type = "ui_extension"
uid = "9db01b0f-c1fe-4d0f-8833-c8f77dbf292f"

[[extensions.targeting]]
module = "./src/ProductExtension.jsx"
target = "admin.product-purchase-option.action.render"
removable = false

[[extensions.targeting]]
module = "./src/ProductVariantExtension.jsx"
target = "admin.product-variant-purchase-option.action.render"
removable = false