api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "admin-update"
type = "ui_extension"
uid = "23a785b6-73c6-d8ee-a9ae-7d9a9bc5d051526a3cb5"

[[extensions.targeting]]
module = "./src/ProductExtension.jsx"
target = "admin.product-purchase-option.action.render"
removable = false

[[extensions.targeting]]
module = "./src/ProductVariantExtension.jsx"
target = "admin.product-variant-purchase-option.action.render"
removable = false